COMMON: &common #标识
  DEBUG: False
  SECRET_KEY: insecure
  # 页码设置
  DEFAULT_PAGE_INDEX: 1
  DEFAULT_PAGE_SIZE: 10

  # 数据库连接
  SQLALCHEMY_DATABASE_URI: 'sqlite:///reconstruction.db'
  SQLALCHEMY_TRACK_MODIFICATIONS: False

  # 算法端地址
  ALGORITHM_URL: http://118.202.10.58:5001

  # 日志配置文件路径
  LOGGING_CONFIG_PATH: ./config/logging.yaml
  # 日志文件存放位置
  LOGGING_PATH: ./logs
  # 响应消息
  RESPONSE_MESSAGE: ./config/msg.yaml

  # 邮件配置
  MAIL_SERVER: 'smtp.163.com'
  MAIL_PORT: 25 # 25 465
  MAIL_USERNAME: 'neu_aning@163.com'
  MAIL_PASSWORD: TOECGEADFVVKUIVT

  # 文件配置
  UPLOAD_FOLDER: ./video  # 上传文件夹路径
  ALLOWED_EXTENSIONS: {'mp4', 'avi', 'mov', 'flv'}  # 允许的视频文件扩展名

  ROOT_PATH: ./

  # redis配置
  # REDIS_EXPIRE: 60*60
  REDIS_HOST: 127.0.0.1
  REDIS_PORT: 6379
  REDIS_DB: 1





DEVELOPMENT: &development
  <<: *common # 继承common，没有重新定义的变量，使用common变量值
  DEBUG: True

STAGING: &staging
  <<: *common
  SECRET_KEY: sortasecure

PRODUCTION: &production
  <<: *common
  SECRET_KEY: mdd1##$$%^!DSA#FDSF
  REDIS_HOST: flask_redis